### ISSUE TITLE
[kumo] Preview with new change FAILS without proper message

### ISSUE THREAD

**Issue by lony** [glomex/gcdt#126]
IF a stack has no changes kumo reports just FAILED and not because there are no changes

If you then look in the UI, you see the following message:
FAILED - The submitted information didn't contain changes. Submit different information to create a change set.

**Comment by markfink** [comment]
now we print out the 'StatusReason':
``` bash
$ kumo preview
MoinMoin fin0007m!
`kumo deploy` would update the following resources:
The submitted information didn't contain changes. Submit different information to create a change set.
Bye fin0007m. Talk to you soon!
```
