### ISSUE TITLE
Add --override-stack-policy for kumo delete

### ISSUE THREAD

**Issue by henriknaknese** [glomex/gcdt#129]
Currently it's not possible to delete stack with "protective" stack policies, imo the tool should allow this from the command line (extend --override-stack-policy)

**Comment by markfink** [comment]
on first glance I do not see a possibility to implement this user story in the proposed way. From the API docs I see two parts that might make sense (RetainResources, RoleARN). @webratz what do you think?

docu here: http://botocore.readthedocs.io/en/latest/reference/services/cloudformation.html#CloudFormation.Client.delete_stack
for convenience I copied the two relevant sections here:

## RetainResources
For stacks in the DELETE_FAILED state, a list of resource logical IDs that are associated with the resources you want to retain. During deletion, AWS CloudFormation deletes the stack but does not delete the retained resources.

Retaining resources is useful when you cannot delete a resource, such as a non-empty S3 bucket, but you want to delete the stack.

## RoleARN
The Amazon Resource Name (ARN) of an AWS Identity and Access Management (IAM) role that AWS CloudFormation assumes to delete the stack. AWS CloudFormation uses the role's credentials to make calls on your behalf.

If you don't specify a value, AWS CloudFormation uses the role that was previously associated with the stack. If no role is available, AWS CloudFormation uses a temporary session that is generated from your user credentials.

**Comment by markfink** [comment]
@webratz any thoughts on that one?

**Comment by webratz** [comment]
I agree that stack protection on an actual delete of the stack does not make sense.
I think the RetainResources would be cool to have to keep some parts like S3 buckets or maybe RDS instances. But if I understand it correctly the Retain is only possible in a DELETE_FAILED state and not on a normal delete.

The RoleARN is already implemented in another ticket and could be used to fix the issue Henrik described, altough  I don't think that anybody would really create a role for just deleting.

**Comment by markfink** [comment]
agreed, I just noticed that for `RetainResources` we would have to provide a list of resources that we want to retain... which is probably not really feasible on the command line.
I think if configured the roleArn should be used for delete. but like you suggested I implement this with #162.
so I close this as wontfix.
