### ISSUE TITLE
[glomex-checks] feature: deployment warnings

### ISSUE THREAD

**Issue by webratz** [glomex/gcdt#154]
At glomex we agreed on several deployment rules

> Basic Deployment Rules as discussed with MM:
> - No deployments in the afternoon (after 2 pm)
> - No deployments on Friday (unless everybody gonna die)
> - No feature gets deployed on prod without QA approval
> - Annonce beforehand the deployments
> - When Traffic starts to peak, we need to see where traffic is low for deployments
> 
> —> for now we check every daily if there is a deployment to do. If yes, we announce it in the slack channel and schedule it to 11 am

These are often ignored, it would be nice to have a way to configure some time and environment constraints and warn the users that he is ignoring rules. Of course there should be an override flag availlable.

This is just a nice to have and should be treated with low priority

**Comment by markfink** [comment]
implemented the check as a `warning` not an `error` so the deployment will continue.
