### ISSUE TITLE
[kumo] use special role for cloudformation deployments

### ISSUE THREAD

**Issue by webratz** [glomex/gcdt#162]
There is a new Feature in CloudFormation which lets a User specify a Role which shall be used to execute the Stack.
This would allow us to reduce users rights, but allow them to handle everything via cloudformation.

Docs can be found at http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html  (Parameter RoleARN)

At a first glance this seems easy to implement as optional config option.

**Comment by markfink** [comment]
@webratz I hope this is what you had in mind... please check and let me know
I closed the ticket for now - lets open a defect in case we need to fix something...

**Comment by markfink** [comment]
need to implement this for delete as well (see #129)
