### ISSUE TITLE
[gcdt-bundler, ramuda] deployment continues after failing dependencies

### ISSUE THREAD

**Issue by jbrandstetter** [glomex/gcdt#181]
Hi,

after forgetting to turn on my VPN to access our repo server I got this output:

(gcdt_venv)  ~/Documents/P7S1/git/ops-captaincrunch-slack/lambda ⮀ master● ⮀ 6d20h51m ⮀ ramuda deploy                                                                                 ⮂
Error running command: ['pip', 'install', '-r', 'requirements.txt', '-t', './vendored'] resulted in the following error:  Collecting glomex-utils==0.0.13 (from -r requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10b0e2410>, 'Connection to reposerver-prod-eu-west-1.infra.glomex.cloud timed out. (connect timeout=5.0)')': /pypi/packages/glomex-utils/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10b0e2350>, 'Connection to reposerver-prod-eu-west-1.infra.glomex.cloud timed out. (connect timeout=5.0)')': /pypi/packages/glomex-utils/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10b0e2590>, 'Connection to reposerver-prod-eu-west-1.infra.glomex.cloud timed out. (connect timeout=5.0)')': /pypi/packages/glomex-utils/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10b0e26d0>, 'Connection to reposerver-prod-eu-west-1.infra.glomex.cloud timed out. (connect timeout=5.0)')': /pypi/packages/glomex-utils/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10b0e2810>, 'Connection to reposerver-prod-eu-west-1.infra.glomex.cloud timed out. (connect timeout=5.0)')': /pypi/packages/glomex-utils/
  Could not find a version that satisfies the requirement glomex-utils==0.0.13 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for glomex-utils==0.0.13 (from -r requirements.txt (line 1))
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
╒══════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════╕
│ CodeSha256   │ 8xXuEYCz+HZjhdp/tscEsbgJAGCZqZPb2PulloJjAPY=                                                           │
├──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ FunctionName │ ops-dev-captain-crunch-slack-notifier                                                                  │
├──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ CodeSize     │ 6494924                                                                                                │
├──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ MemorySize   │ 128                                                                                                    │
├──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ FunctionArn  │ arn:aws:lambda:eu-west-1:420189626185:function:ops-dev-captain-crunch-slack-notifier                   │
├──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Version      │ $LATEST                                                                                                │
├──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Role         │ arn:aws:iam::420189626185:role/lambda/ops-dev-captain-crunch-sl-LambdaCaptainCrunchSlack-132QX0DBUEJ6B │
├──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Timeout      │ 30                                                                                                     │
├──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ LastModified │ 2016-11-11T08:29:12.254+0000                                                                           │
├──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Handler      │ handler.lambda_handler                                                                                 │
├──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Runtime      │ python2.7                                                                                              │
├──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Description  │ Notifies slack about who is Captain Crunch                                                             │
╘══════════════╧════════════════════════════════════════════════════════════════════════════════════════════════════════╛
Great you're already accepting a ping in your Lambda function

At first I thought it got deployed instead of the error. Turns out it didn't but I was still confused. ramuda should exit with an error message after the failing step and not continue.

**Comment by markfink** [comment]
actual behaviour:
* deployment continues after failing pip requirement (requirement glomex-utils==0.0.13)

expected:
* ramuda should exit with an error message after the failing step.

sidenote: the `glomex-checks` plugin should prevent you from working without VPN

**Comment by markfink** [comment]
new gcdt-bundler output:
```
$ ramuda bundle
MoinMoin fin0007m!
Please consider an update to gcdt version: 0.1.401
ERROR: ramuda gcdt-bundler: Unable to install pip dependencies for your AWS Lambda function.
```

with the `-v` option:
```
$ ramuda bundle -v
...
Collecting notfound==0.8.15 (from -r requirements.txt (line 2))
  Could not find a version that satisfies the requirement notfound==0.8.15 (from -r requirements.txt (line 2)) (from versions: 1.0.0, 1.0.1, 1.0.2)
No matching distribution found for notfound==0.8.15 (from -r requirements.txt (line 2))

DEBUG: bundler: 307: Unable to install pip dependencies for your AWS Lambda function.
ERROR: ramuda gcdt-bundler: Unable to install pip dependencies for your AWS Lambda function.
```
