### ISSUE TITLE
[kumo] Parameter diffing flaws

### ISSUE THREAD

**Issue by ludwigm** [glomex/gcdt#184]
If params have NoEcho=True they will be displayed which is really bad if this are passwords. Also changes are reported with parameter lists (comma seperated). This is something which was already fixed in the past.

**Comment by markfink** [comment]
no, I can not find that this was implemented in the past

`NoEcho=True` parameters come back as '****' so we could not and can not diff and decide whether there was a change or not. I believe this issue is focused on the `display` aspect so I display the new value with the same pattern like this: 
```
╒══════════════╤═══════════════╤═══════════╕
│ Parameter    │ Current Value │ New Value │
├──────────────┼───────────────┼───────────┤
│ my_secret    │ ****          │ ****      │
╘══════════════╧═══════════════╧═══════════╛
```
