### ISSUE TITLE
[kumo] add SNS notification

### ISSUE THREAD

**Issue by webratz** [glomex/gcdt#185]
Several services could emit events to SNS. These events could be sent to our default DataDog queue so they can be used as event overlays there and offer the options for better monitoring.

Services that support it:
* Cloudformation: http://boto3.readthedocs.io/en/latest/reference/services/cloudformation.html#CloudFormation.Stack.notification_arns
* CodeDeploy: http://boto3.readthedocs.io/en/latest/reference/services/codedeploy.html#CodeDeploy.Client.create_deployment_group (triggerConfigurations)

**Comment by markfink** [comment]
@webratz if I understand you correctly, you want to make this configurable via kumo & tenkai config files?

**Comment by webratz** [comment]
Indeed, altough I think one could already configure that for the DeploymentGroup within the Cloudformation template.
So it would only be for Cloudformation / kumo

**Comment by markfink** [comment]
docs here: http://gcdt.readthedocs.io/en/latest/20_kumo.html#configuring-notificationarns-for-a-cloudformation-stack
