### ISSUE TITLE
[glomex_config_reader plugin] Flexible config files

### ISSUE THREAD

**Issue by ludwigm** [glomex/gcdt#186]
![image](https://cloud.githubusercontent.com/assets/471035/20625471/e1be2cc0-b313-11e6-8d75-aee53996ba1d.png)

![image](https://cloud.githubusercontent.com/assets/471035/20625477/ed246ff2-b313-11e6-81b2-65028511df08.png)

Proposal:
```
# settings_common.conf automatically loaded if available
kumo {
    stackName = "IngestAPI"
    artifactBucket = "7finity-videoinfra-dev-deployment"
    otherNonCfParam = "value"

    cloudFormationParams {
        cfParamInCamelCase = "param-value"
    }
}

unrelatedSectionForOtherUseCases {

}
```

https://confluence.glomex.com/display/MDP/Versioning

**Comment by markfink** [comment]
the gcdt-config-reader has this feature already. I think this is a pretty good alternative.
