### ISSUE TITLE
[ramuda] configure cloudwatch logs

### ISSUE THREAD

**Issue by webratz** [glomex/gcdt#191]
Every lambda logs to a Cloudwatch Logs Group named after the following schema `/aws/lambda/<function name>`. Per default there is no retention period.

This results in many logs, that are never deleted but need to be paid for.

It would be great to have a way in ramuda to actually configure the retention period for the log group and probably even delete it when decomissioning the lambda.

**Comment by markfink** [comment]
I believe this is going to be useful! I think this comprises the following parts:
1) add in the `lambda` section of the config:
```
lambda {
    ...
    logs {
        retentionInDays = 90
    }
}
If this configuration is missing we will get a default retention of `forever`, or do you think we should set a shorter default retention time of say 180 days? 

2) add option --delete--logs to `ramuda delete` to delete all logs in the log group

**Comment by webratz** [comment]
currently I don't have a good lambda function to test that is deployed via ramuda :(

**Comment by markfink** [comment]
json issue is fixed here: https://github.com/glomex/gcdt/pull/326

regarding test samples... we have some simple but different lambda samples here:
https://github.com/glomex/gcdt/tree/develop/tests/resources
