### ISSUE TITLE
[gcdt] I need logging in gcdt to debug the captaincrunch alexa skill

### ISSUE THREAD

**Issue by markfink** [glomex/gcdt#247]
@jbrandstetter you said you need this for debugging purposes. Could you please specify in more detail what you are tying to achieve. Does CloudWatch have the data? Maybe you need to add some logging to the alexa skill. Why is this a gcdt issue? I think a sample scenario could be helpful.

**Comment by markfink** [comment]
@jbrandstetter there was no progress with this one for some time. Any feedback / news?

**Comment by jbrandstetter** [comment]
Hi,

i would like to be able to access logs for the current (or an arbitrary) lambda function from within ramuda:

ramuda logs <--lambda>

What I expect is the output of the cloudwatch logs logstream for this lambda function. Basically the functionality of https://github.com/jorgebastida/awslogs but from within ramuda. 

Does that make more sense now?

**Comment by markfink** [comment]
yes, thank you this makes total sense. 
are you thinking about just the last lines / the last call / all logs or a more interactive feature like less / tail?

**Comment by webratz** [comment]
personally I think a `less` like behaviour would be awesome as you can also search through it.
But there might be other use cases (eg piping to other tools) where less is suboptimal.

**Comment by markfink** [comment]
maybe a `--tail` option? not as much implementation effort as a full 'less' implementation but might get us a log way. We need to define some meaningful defaults for this! Probably easiest to discuss this in person...

**Comment by markfink** [comment]
AWS console:
![image](https://user-images.githubusercontent.com/33456/27949411-e6b69a42-62fd-11e7-8ac5-951b742d8e3d.png)

same in the terminal:
```
$ ramuda logs ops-dev-captain-crunch-slack-notifier
MoinMoin fin0007m!
Please consider an update to gcdt version: 0.1.412
2017-07-07
07:00:32  START RequestId: f75cd7de-62e1-11e7-937d-ef5726c6f5c8 Version: $LATEST
07:00:36  END RequestId: f75cd7de-62e1-11e7-937d-ef5726c6f5c8
07:00:36  REPORT RequestId: f75cd7de-62e1-11e7-937d-ef5726c6f5c8        Duration: 4221.50 ms    Billed Duration: 4300 ms        Memory Size: 128 MB     Max Memory Used: 43 MB
Bye fin0007m. Talk to you soon!
```
