### ISSUE TITLE
[ramuda] add nodejs6.10 support

### ISSUE THREAD

**Issue by markfink** [glomex/gcdt#254]
need to be able to select nodejs4.3 and nodejs6.10

**Comment by olysyuk** [comment]
need this functionality

**Comment by markfink** [comment]
our test case works well with the nodejs4.3 runtime
but the required npm modules can not be installed with the nodejs6.10 runtime: https://github.com/DiegoRBaquero/node-1337/issues/1
we can probably use another module for the test but it proves that there are definitely differences in the nodejs runtime and we need to consider these differences in the gcdt-bundler.
