### ISSUE TITLE
[ramuda] add ENV support for variables

### ISSUE THREAD

**Issue by markfink** [glomex/gcdt#262]
http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html
I opened the ticket on behalf of @Tonkonozhenko 

this is the usecase (nodejs):
https://github.com/glomex/mes-ruby-base-infrastructure/pull/48/files#diff-7395ec9757643c705252df9970606918R30

**Comment by Tonkonozhenko** [comment]
Hi @markfink
Do you have any progress on this task?

**Comment by markfink** [comment]
I added a testcase based on the AWS Lambda function you gave me yesterday (https://github.com/glomex/gcdt/pull/317) - also merged the changelog. We release it this afternoon.
