### ISSUE TITLE
[gcdt_config_reader] reference to base config file

### ISSUE THREAD

**Issue by markfink** [glomex/gcdt#263]
for the json / python `gcdt_config_reader` plugin we need a `baseconfig` property which gives a basepath.

my_special_baseconfig.json
-> gcdt_dev.json
-> gcdt_stage.json

config values can be overridden by the dependent gcdt_<env>.json file.
this ticket was opened on behalf of @Tonkonozhenko

**Comment by markfink** [comment]
docs here: http://gcdt.readthedocs.io/en/latest/gcdt_plugins/38_gcdt_config_reader.html#reference-to-base-config-file

**Comment by Tonkonozhenko** [comment]
@markfink 
 I have a lambda with SNS connection so I'll do it soon. Thanks!

**Comment by markfink** [comment]
@Tonkonozhenko you requested this - do you want to take a look?
