### ISSUE TITLE
[ramuda] more flexible event wiring

### ISSUE THREAD

**Issue by markfink** [glomex/gcdt#264]
currently only wiring for s3 and time_events are implemented

find a more flexible event wiring implementation so we can have more event sources.
need to cover at least the following sources:
* SNS

this ticket was opened on behalf or @Tonkonozhenko

**Comment by Tonkonozhenko** [comment]
Hi @markfink 
Do you have any progress on this task?

**Comment by markfink** [comment]
AWS has many event sources: http://docs.aws.amazon.com/lambda/latest/dg/eventsources.html
in regard to this issue the SRE squad recently discussed the Zappa event wiring (@jbrandstetter thank you for the introduction of the topic!):
https://github.com/Miserlou/Zappa#executing-in-response-to-aws-events

to use this more flexible mechanism in gcdt would help us to use many events not just SNS

sample SNS event config from Zappa docu:
```
        "events": [
            {
                "function": "your_module.your_function",
                "event_source": {
                    "arn":  "arn:aws:sns:::your-event-topic-arn",
                    "events": [
                        "sns:Publish"
                    ]
                }
            }
        ]
```

**Comment by markfink** [comment]
added docs on events config here: http://gcdt.readthedocs.io/en/latest/40_ramuda.html#adding-a-settings-json-file
@jbrandstetter : you want to take a look?

**Comment by jbrandstetter** [comment]
Hi, great work! I'm just confused by this sentence from the docs:
 These functions will be packaged and deployed along with your app_function
Aren't we scheduling calls to the actual Lambda and not some other sideloaded code?

**Comment by markfink** [comment]
yeah, I see how this can be confusing. I refered to the exotic case of using lambda as a webservice implementation behind API Gateway. if there is no gru app, then nothing is packaged alongside. I am going to make this more obvious
