### ISSUE TITLE
[gcdt] add support for Python 3.6

### ISSUE THREAD

**Issue by jbrandstetter** [glomex/gcdt#283]
AWS recently announced support for Python 3.6 in Lambda: https://aws.amazon.com/releasenotes/5198208415517126

I think for this to work we need to have a new bundler and a flag for the runtime. We should also check support for Python 3 for gcdt in general as it probably doesn't make sense to mix the two versions for deployments.

**Comment by markfink** [comment]
the python36 runtime support is done. for general gcdt python36 support I need to commit relevant changes to relevant plugins like gcdt-lookups etc. I'll keep the ticket open till this is done.
