### ISSUE TITLE
[tenkai] Improve output in case of errors

### ISSUE THREAD

**Issue by webratz** [glomex/gcdt#316]
While tenkai shows the state of a deployment (success and fail) it does not show any further information to help debugging in the case of a failed deployment.

So I suggest three improvements here, that we then maybe split up into separate issues when needed.

## Show Instances
CodeDeploy shows in the UI for Deployments the state of each instances that was deployed to. A Short overview with Information like
* Instance ID
* Status
* Most recent event
* (if there are errors): output (see next point)
at the end of the deployment would be really helpful to find out which instances failed.
![bildschirmfoto 2017-06-29 um 15 36 01](https://user-images.githubusercontent.com/2162832/27690434-9d05d6e6-5ce1-11e7-986f-317daf0314d4.png)

## Show Failed Events Logs
In case of a failure during on of the CodeDeploy Agents steps it is possible via the AWS UI to get a log of stdout of the failed steps.
This log should be shown per instances in the view described above
![bildschirmfoto 2017-06-29 um 15 38 01](https://user-images.githubusercontent.com/2162832/27690433-9d04b18a-5ce1-11e7-9fe7-d160417bd203.png)

## Show CloudWatch Logs
This is something that is a bit specific to our glomex setup but still may be useful for others.
Our Instances send the contents of `/var/log/messages` to CloudWatch logs to a log group named `/var/log/messages` where the stream name is then the instance id.

It would be great to have that as optional output (via a parameter) in case of a failure for further debugging.

**Comment by markfink** [comment]
this ticket is pretty well defined. again thank you for that.
regarding **Cloudwatch logs:**
* only thing left is "have that as optional output (via a parameter) in case of a failure". I did not understand that part. Do you want to have a way to silence the cloudwatch logs from the command line like with an "--no-logs" option?
* I limited the output to the duration of the deployment.
* I made the loggroup configurable:

```
    "tenkai": {
        "bundling": {
            "folders": [
                {
                    "source": "./codedeploy",
                    "target": "."
                },
                ...
            ]
        },
        "codedeploy": {
            "applicationName": "lookup:stack:gcdt-sample-stack:applicationName",
            "artifactsBucket": "7finity-infra-dev-deployment",
            "deploymentConfigName": "lookup:stack:gcdt-sample-stack:DeploymentConfig",
            "deploymentGroupName": "lookup:stack:gcdt-sample-stack:DeploymentGroup"
        },
        "deployment": {
            "LogGroup": "/my/loggroup"
        }
    }
```

sample tenkai output of a **failed** deployment:

```
Deployment: d-VZJ6EZODN -> URL: https://eu-west-1.console.aws.amazon.com/codedeploy/home?region=eu-west-1#/deployments/d-VZJ6EZODN
Deployment: d-VZJ6EZODN - State: Created
Deployment: d-VZJ6EZODN - State: InProgress
Deployment: d-VZJ6EZODN - State: InProgress
Deployment: d-VZJ6EZODN failed: {
  "message": "The overall deployment failed because too many individual instances failed deployment, too few healthy instances are available for deployment, or some instances in your deployment group are experiencing problems.", 
  "code": "HEALTH_CONSTRAINTS"
}

deployment summary:
Instance ID            Status       Most recent event
i-040d4f5ceb83fa467    Failed       ValidateService

deployment diagnostics:
Instance ID: i-040d4f5ceb83fa467
Error Code:  ScriptFailed
Script Name: verify_service.sh
Message:     Script at specified location: verify_service.sh run as user root failed with exit code 1
Log Tail:    LifecycleEvent - ValidateService
Script - verify_service.sh
[stderr]/opt/codedeploy-agent/deployment-root/4fe5fdf4-a1ae-4a59-a907-7301e57b071c/d-VZJ6EZODN/deployment-archive/verify_service.sh: line 7: booooooom: command not found

instance i-040d4f5ceb83fa467 logentries  during codedeploy run
Jul 21 07:54:59 ip-172-29-5-80 su: (to root) root on none
Jul 21 07:55:03 ip-172-29-5-80 su: (to root) root on none
Jul 21 07:55:03 ip-172-29-5-80 logger: gcdt-sample-stack-unittestGcdtSupercarsToySample-91VB1G5YIL88 - d-VZJ6EZODN - gcdt-sample-stack-unittestGcdtSupercarsToySampleDg-195232ZMR8222 - 4fe5fdf4-a1ae-4a59-a907-7301e57b071c AfterInstall
Jul 21 07:55:03 ip-172-29-5-80 logger: install dependencies
Jul 21 07:55:04 ip-172-29-5-80 logger: copy files from bundle to destination
Jul 21 07:55:04 ip-172-29-5-80 logger: finished copy files from bundle to destination
Jul 21 07:55:04 ip-172-29-5-80 logger: finished after install script
Jul 21 07:55:06 ip-172-29-5-80 su: (to root) root on none
Jul 21 07:55:08 ip-172-29-5-80 su: (to root) root on none
```

**Comment by webratz** [comment]
The idea was to only enabled it on demand, but i guess default is also fine.
What happens in case the (default) log group does not exist?

**Comment by markfink** [comment]
@webratz the diagnostics function checks if the defined | default log group and instance log stream exists and outputs the logs for the deployment duration. If either log group or log stream does not exist then it outputs.nothing
