### ISSUE TITLE
[yugen] cache settings

### ISSUE THREAD

**Issue by ateraz** [glomex/gcdt#328]
Currently yugen does not support enabling API cache and setting cache parameters. This should be possible by specifying cache-related params when performing `create_deployment` call, more documentation available [here](http://boto3.readthedocs.io/en/latest/reference/services/apigateway.html#APIGateway.Client.create_deployment).

**Comment by markfink** [comment]
@ateraz Current version for gcdt means 0.1.417 -  just to make sure which version are you using? 
You are talking about `authorizerResultTtlInSeconds`?
how do you want to specify the cache related params? as yugen optinos, or in config?

**Comment by ateraz** [comment]
@markfink I'm talking about params like stage's `cacheClusterEnabled` and method's `cachingEnabled ` for [API Gateway stage](http://docs.aws.amazon.com/apigateway/api-reference/resource/stage/). None of gcdt versions support that.
The most consistent way to specify cache related params would be in config, as we do with all the params

**Comment by markfink** [comment]
@ateraz I asked for the version you currently use because if I add this to 0.1.421 or later and you are pinned to 0.0.59 you still can not not benefit from an improvement. So unless you claim that you are on current versions this has no priority for us.

**Comment by ateraz** [comment]
@markfink I understand that I would not have any effect on previous gcdt versions. We can easily upgrade to the latest gcdt version for deploying our API once this feature is available.

**Comment by markfink** [comment]
I added the `cacheClusterEnabled` setting so it can be used in the 'api' section of the config.
Yugen does not implement the `cachingEnabled` method so this is covered by the `create_deployment` method alone.
`false` is the default for `cacheClusterEnabled` and I kept it this way so existing configs won't break.
@ateraz I hope this solves the issue for you - please help with the testing like we agreed.

**Comment by markfink** [comment]
@ateraz just confirmed via slack to test and give feedback until end of the week

**Comment by markfink** [comment]
docs for methodSettings here: http://gcdt.readthedocs.io/en/latest/50_yugen.html#folder-layout

**Comment by markfink** [comment]
just got some nice feedback from @ateraz :-)
```
...
overriding caching settings for endpoint worked
i’m sure it would work for the other properties, but have not checked them because we’re not using those
...
sounds great. so we are done?
...
yep, everything we needed is there now
thanks for a great work!
```

**Comment by markfink** [comment]
reopened the ticket on behalf of @Arfua 
```
we need your help to overcome issue with deployment and caching enabled.
there is strange behavior. when we deployed api with caching at stage we got this error:

create deployment
ERROR: An error occurred (BadRequestException) when calling the CreateDeployment operation: Invalid stage cache size: null
ERROR: An error occurred (BadRequestException) when calling the CreateDeployment operation: Invalid stage cache size: null
Add Comment


after that we enabled and disabled it with UI, and now we do not have this error.
but it will be back when we do PROD deployment and try to deploy caching the first time again

may you please add parameter cacheClusterSize=‘0.5’ to create_deployment function in new version of gcdt ?

it is in yugen_core, we tested that with this parameter there is no this error
```
