### ISSUE TITLE
[kumo] commands to stop / start stack

### ISSUE THREAD

**Issue by markfink** [glomex/gcdt#342]
as discussed in the SRE planning for Q3 on 6th of June 2017 we need this mechanism to stop / start our dev & test - infrastructure during nights / weekends:

* stop instances
* stop RDS
* resize autoscaling groups to 0

# commands

two new kumo commands to use this feature:

* `kumo stop`
* `kumo start`

# configuration

Add optional attribute `DisableStop` so we can prevent parts of our infrastructure from this in case the application is not yet ready for it.

```bash
{
  "kumo": {
    "stack": {
      "StackName": "gcdt-sample-stack"
    }
    "parameters": {
      "VPCId": "lookup:stack:<stack-name>:DefaultVPCId",
      "ScaleMinCapacity": "1",
      "ScaleMaxCapacity": "1",
      "InstanceType": "t2.micro",
      "DefaultInstancePolicyARN": "lookup:stack:<stack-name>:DefaultInstancePolicyARN",
      "AMI": "lookup:baseami"
    }
    "deployment": {
      "DisableStop": true
    }
  }
}
```

@jbrandstetter, @webratz anything to add?

**Comment by webratz** [comment]
I think that is fine.
`DisableStop` would then be for the whole Stack, right?
As soon as we have some sort of automated monitoring configuration, we probably should also set a downtime / maintenance period then.

**Comment by markfink** [comment]
docs here:
http://gcdt.readthedocs.io/en/latest/20_kumo.html#stop
http://gcdt.readthedocs.io/en/latest/20_kumo.html#start

**Comment by c0un7-z3r0** [comment]
Tested `kumo stop` and `kumo start` on a single instance stack (powermams-xml-importer) and its working as expected
