### ISSUE TITLE
[kumo] Bug: kumo considers cloudformation done when security token expires

### ISSUE THREAD

**Issue by jbrandstetter** [glomex/gcdt#343]
Hi,

I had a longer CF deployment today which brought my security token to expire. An Exception occurred and kumo thought that CF deployment has finished and began to execute post hooks. 
This could lead to a lot of messy things. See the screenshot here for more details: http://imgur.com/a/JovtM

Excpected behaviour:
I would expect kumo to honour the exception and exit without any further execution of (lifecycle) hooks

Cheers,

Johannes

**Comment by webratz** [comment]
While I agree that gcdt should handle that properly: As the token is expired the post hooks should fail also which leads (in an ugly way) to the actual expected result, right?

**Comment by jbrandstetter** [comment]
Not necessarily, since you can execute arbitrary code there stuff might break if you do stuff outside of AWS scope (I'm configuring pingdom checks at one point for example).

**Comment by markfink** [comment]
I did some research and experiments adding aws-mfa functionality to gcdt as a plugin (#371) and it looks very promising.
an alternative way to tackle the token-expiry-issue is to refresh the token via the #371 plugin before the deployment. @jbrandstetter @webratz do you think this would a viable solution to resolve the issue for you?

**Comment by webratz** [comment]
so if i understand the description right, that would mean a deployment may only last up to 60 minutes, as the session is only refreshed on a deployment start?

**Comment by markfink** [comment]
@jbrandstetter I was thinking this refers to our fine lifecycle hooks (http://gcdt.readthedocs.io/en/latest/20_kumo.html#kumo-lifecycle-hooks).
but I just realised that this uses the old and long deprecated hook mechanism. Please do not use the old hook mechanism any more. 
BTW. if you want to continue using the old hook mechanism you need to pin gcdt versions like described here (http://gcdt.readthedocs.io/en/latest/07_installation.html#dependency-specification-pinning-versions). The upcoming gcdt 0.2.x won't support the old mechanism any longer.
