### ISSUE TITLE
[kumo] improve template support

### ISSUE THREAD

**Issue by markfink** [glomex/gcdt#353]
two improvements:

1) kumo to add `stack_output` to context so it can be used in hooks (e.g. `command_finalized`). I think @olysyuk asked for a similar feature this week so eventbus registration can be implemented within the template.

2) kumo to provide `context` and `config` to the `generate_template` function of a template as parameters in case they are contained in the signature. existing templates without the parameters are not to be touched and will continue to work.

**Comment by markfink** [comment]
@olysyuk I discussed your requirement for stack_output in the template with @webratz and we think the described solution would be a viable solution for it. Could you please check if this meets your requirement.

**Comment by olysyuk** [comment]
Idea with stack_output in context is very good.

**Comment by markfink** [comment]
docs here:
http://gcdt.readthedocs.io/en/latest/20_kumo.html#accessing-context-and-config-in-cloudformation
http://gcdt.readthedocs.io/en/latest/20_kumo.html#kumo-lifecycle-hooks
@olysyuk do you want to take a look
