### ISSUE TITLE
[gcdt-lookups] new ACM lookup

### ISSUE THREAD

**Issue by webratz** [glomex/gcdt#359]
the current ssl lookup is flawed, and managing SSL certificates via IAM is sort of deprecated by AWS.
kiso already supports adding certs to ACM already for a while, so having a lookup makes sense.

I propose the following way to implement it:

* pass a list of hostnames that should be secured.
* check all certificates in ACM if the configured CN (`DomainName`) or SANs (`SubjectAlternativeNames`) (including wildcards) if they match for the given list of hostnames
* the chosen certificates `STATUS` must be `ISSUED`
* if there are multiple matches, use the one with the most distant expiry date
* return the ARN of the certificate
* wildcards for hosted zone are expressed with "*."
* 'ERROR' in case a suitable certificate can not be found

sample: `lookup:acm:foo.mes.glomex.cloud:supercars.infra.glomex.cloud:*.dev.infra.glomex.cloud`

**Comment by Dgadavin** [comment]
Maybe we can provide it like a list. 
``` json
"SslCerts": ["lookup:acm:foo.mes.glomex.cloud", "lookup:acm:supercars.infra.glomex.cloud"]
```
For me such syntax much more readable.

**Comment by webratz** [comment]
Indeed its not very readable, but your suggestion implies that this is a list of lookups where each one would have an individual return value.
In this case there may only be exactly one return value, an certificate ARN.

**Comment by markfink** [comment]
I do not think to refactor the parameter format of the lookup mechanism is not feasible before 18th of August.

**Comment by markfink** [comment]
@webratz @Dgadavin is this the solution we need / want to implement?

**Comment by webratz** [comment]
sounds good for me.
improving the lookup syntax should maybe be a separate ticket. if wanted i can make a proposal

**Comment by Dgadavin** [comment]
I think if it easy and quick to implement let's do this without improving lookup syntax

**Comment by markfink** [comment]
@webratz @Dgadavin I just released the new acm lookup. I am convinced it meets your requirements and I hope you like it.
Please try it out and let me know
@webratz thank you for the review and support

**Comment by webratz** [comment]
tested on one stack. seems to work fine.
thank you!
