### ISSUE TITLE
[kumo]stop/start command issues

### ISSUE THREAD

**Issue by Dgadavin** [glomex/gcdt#376]
I tried use `kumo stop` with Jenkins and have some issue. 
If I use `kumo stop` once and after that I run `kumo stop` one more time on the same stack it stuck with 

```bash
Resize autoscaling group 'AutoscalingGroup' to minSize=0, maxSize=0
[31mERROR: Waiter InstanceTerminated failed: Max attempts exceeded[39m
[34mDEBUG: gcdt_lifecycle: 154: Waiter InstanceTerminated failed: Max attempts exceeded[39m
[31mERROR: Waiter InstanceTerminated failed: Max attempts exceeded[39m
Build step 'Execute shell' marked build as failure
```

I think we can add additional checks if `ASG` is already zero don't do anything. 

Other, maybe bug, what I saw. Randomly `kumo` can't find stack in `lookup` If I run job one more time it became normal other time it continue failing with same error 

```bash
[34mDEBUG: gcdt_lifecycle: 88: ### check_credentials_init[39m
[34mDEBUG: gcdt_lifecycle: 90: ### check_credentials_finalized[39m
[34mDEBUG: lookups: 76: Stack 'mes-shared-infrastructure-qa' does not exist.[39m
[31mERROR: Stack 'mes-shared-infrastructure-qa' does not exist.[39m
[34mDEBUG: gcdt_lifecycle: 98: ### lookup_init[39m
[34mDEBUG: gcdt_lifecycle: 100: ### lookup_finalized[39m
[34mDEBUG: gcdt_lifecycle: 101: ### config after lookup:[39m
```
I checked and stack exist.

**Comment by Dgadavin** [comment]
I found that if I start 4+ jenkins jobs I have this error 
```bash 
An error occurred (Throttling) when calling the DescribeStacks operation (reached max retries: 4): Rate exceeded
```
If I start 2 jobs everything is Ok.

**Comment by webratz** [comment]
Hi,

I guess we are mostly running into API limits from AWS here. Probably we can add some sort of caching and more intelligent usage.
@markfink is currently on vacation. So as you have found a workaround I'd postpone it until then.

**Comment by Dgadavin** [comment]
Here is an official answer of AWS
```text
I have taken a look at your support case below and was provided with the following information.

In order to remove the rate exceeded throttling error, we usually recommend to either implement "Polling", "Retries" or "Exponential back off" in their API calls.

For more information around this you can take a look at the link below which will should assist you further.

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html

Should you have any further queries please feel free to contact us.

Best regards,

Dominic M.
Amazon Web Services
```

**Comment by markfink** [comment]
discussed on gcdt grooming on 27.09. => do not use gcdt.json config instead provide the stackname as CLI parameter to avoid running lookups.

**Comment by markfink** [comment]
@Dgadavin confirmed via slack that it now works
