### ISSUE TITLE
[ramuda] ecs event_source

### ISSUE THREAD

**Issue by markfink** [glomex/gcdt#383]
opened this issue on behalf of @Dgadavin 

![image](https://user-images.githubusercontent.com/33456/31877191-d4a8bf38-b7d5-11e7-9861-49aeec830689.png)

**Comment by markfink** [comment]
I just looked into it. You have to wire a cloudwatch event. For ECS events you need to configure the event pattern (add **pattern** to your event wiring config):
```
...
"events": [{
  "event_source": {
    "pattern": {your event pattern}
  }
}]
...
```
I looked into the code and this is already implemented. Not tested but I would expect it to work

**Comment by Dgadavin** [comment]
Thanks @markfink. I will try it.

**Comment by Dgadavin** [comment]
Good day @mark. I want to use ramuda wiring for Cloudwatch events. Now ramuda support `Schedule` events like cron. I want to have also events with `event pattern` http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/CloudWatchEventsandEventPatterns.html
I've tried like you mentioned above 
```bash
"events": [
      {
        "event_source": {
          "pattern": {
          "source": [
            "aws.ecs"
          ],
          "detail-type": [
            "ECS Container Instance State Change"
          ]
        }
        }
      }
    ]
```
and I had such error
```bash
DEBUG: gcdt_lifecycle: 106: ### config_validation_init
DEBUG: gcdt_lifecycle: 116: ### config_validation_finalized
DEBUG: gcdt_lifecycle: 129: ### bundle_pre
DEBUG: gcdt_lifecycle: 131: ### bundle_init
DEBUG: gcdt_lifecycle: 133: ### bundle_finalized
DEBUG: gcdt_lifecycle: 141: ### command_init
wiring lambda_arn arn:aws:lambda:eu-west-1:979514658570:function:one-task-per-ecs-instance:ACTIVE ...
ERROR: u'arn'
DEBUG: gcdt_lifecycle: 154: u'arn'
ERROR: u'arn'
```
My example is about ECS event pattern but you can use any event pattern for testing or ping me and I will test it with ECS.

**Comment by markfink** [comment]
WIP; working on a solution right now and I use this comment to document the resolve...

to properly set things up you need to give it a 'name' attribute:
```
"events": [
  {
    "event_source": {
      "name": "ecs_container_instance_state_change",
      "pattern": {
        "source": [
          "aws.ecs"
        ],
        "detail-type": [
          "ECS Container Instance State Change"
        ]
      }
    }
  }
],
```

**Comment by markfink** [comment]
@Dgadavin just confirmed via slack that he has tested the solution and we can release it
