### ISSUE TITLE
[gcdt-bundler] npm install dev dependencies

### ISSUE THREAD

**Issue by markfink** [glomex/gcdt#384]
ticket was opened on behalf of Pascal Matthiesen

please add the details here

**Comment by pmdroid** [comment]
when i now build a bundle with the gcdt-bundler the bundler installs all npm dependencies.

expected: when i build a bundle my code i only want to have request, request-promise-native, url-parse installed this can be achieved my using npm install  --production

```
{
  "name": "serverless",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": { },
  "author": "Pascal Matthiesen <pascal.matthiesen@glomex.com>",
  "license": "Unlicense",
  "devDependencies": {
    "eslint": "^3.19.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^3.0.2",
    "eslint-plugin-react": "^6.10.3",
    "mocha": "^3.5.3",
    "mocha-junit-reporter": "^1.15.0",
    "nyc": "^11.2.1",
    "power-assert": "^1.4.4",
    "sinon": "^3.3.0",
    "micro": "^9.0.0",
    "micro-dev": "^1.2.3"
  },
  "dependencies": {
    "request": "^2.83.0",
    "request-promise-native": "^1.0.5",
    "url-parse": "^1.1.9"
  }
}
```

**Comment by markfink** [comment]
that would be "npm install --only=dev", right?

**Comment by pmdroid** [comment]
@markfink i am not sure i used --production before. i looked into the docs and it looks like the same to me

**Comment by klipstein** [comment]
I always do `NODE_ENV=production` instead. Can we somehow set environment variables on install?

**Comment by markfink** [comment]
@pmdroid I was using the "cmd = ['nodeenv/bin/npm', 'install', '--only=prod']" locally for a while now and I could not find any issues with It. I am going to commit this if you still want it.

**Comment by pmdroid** [comment]
@markfink would be great if you could :thumbsup:
