### ISSUE TITLE
[tenkai] handle signals

### ISSUE THREAD

**Issue by webratz** [glomex/gcdt#40]
tenkai is often running within a Jenkins. It would be great if kumo could detected if a job is being stopped / terminated and then also stop the running deployment in CodeDeploy.

Currently if the user terminates the jenkins job, the deployment will proceed. As the deployment is still running a new one can't be triggered.

**Comment by markfink** [comment]
this feature has been implemented for tenkai deployments and kumo updates.
gcdt now generally receives and logs SIGINT and SIGTERM signals and exits with exit_code 1.

**Comment by markfink** [comment]
just released the feature. please give feedback...
close it for now

**Comment by webratz** [comment]
tested for tenkai, i think the rollback is the correct way todo.
Just was a littlebit surprised that CodeDeploy handles the rollback as a separate deployment.
