### ISSUE TITLE
[kumo] Parameter diffing without params fails

### ISSUE THREAD

**Issue by ludwigm** [glomex/gcdt#64]
Parameter diffing does not work when there are no CloudFormation parameters. Can be seen in the following screen. Probably a guard on "stack.parameters" need to be added. Won't do it directly now because of ongoing refactoring work:

![image](https://cloud.githubusercontent.com/assets/471035/17205145/ca32fc0c-54a9-11e6-8acb-5ac5dc608d65.png)

**Comment by markfink** [comment]
related to / fixed with #184
