### ISSUE TITLE
[kumo] Preview for a new stack

### ISSUE THREAD

**Issue by ludwigm** [glomex/gcdt#73]
Maybe it makes sense to also offer preview for a new stack to see what it would create. Just tried it out and when we do it we will get:

![image](https://cloud.githubusercontent.com/assets/471035/17432034/3c8b002a-5afd-11e6-8baa-da388ad6c19a.png)

**Comment by markfink** [comment]
according to API docs this does look well supported so I try to add it to gcdt
http://botocore.readthedocs.io/en/latest/reference/services/cloudformation.html#CloudFormation.Client.create_change_set
```
To create a change set for a stack that doesn't exist, for the ChangeSetType parameter, specify CREATE 
```

**Comment by markfink** [comment]
just discussed with @jbrandstetter and we decided to go forward with this. After `kumo preview` execution wie remove the pending stack. Another tweak we want to add is to highlight that the stack is not existent like this:
```
Stack 'infra-dev-kumo-sample-stack' does not exist
`kumo deploy` would create the following resources:
╒═══════════════════╤═════════════════╕
│ Action            │ Add             │
├───────────────────┼─────────────────┤
│ ResourceType      │ AWS::S3::Bucket │
├───────────────────┼─────────────────┤
│ Scope             │ []              │
├───────────────────┼─────────────────┤
│ Details           │ []              │
├───────────────────┼─────────────────┤
│ LogicalResourceId │ S3Bucket1       │
╘═══════════════════╧═════════════════╛
```
